name: sweat_lock
description: "Earn your screen time with real push-ups"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  hive_ce: ^2.15.1
  hive_ce_flutter: ^2.3.3
  camera: ^0.11.3
  url_launcher: ^6.3.2
  google_fonts: ^6.3.2
  flutter_gen: ^5.12.0
  fl_chart: ^1.1.1
  percent_indicator: ^4.2.5
  google_mlkit_pose_detection: ^0.14.0
  uuid: ^4.5.1
  permission_handler: ^11.3.1
  flutter_accessibility_service: ^1.0.0
  installed_apps: ^1.5.0
  file_picker: ^8.1.7
  path_provider: ^2.1.5
  path: ^1.9.1
  pdfx: ^2.9.2
  in_app_review: ^2.0.10
  pedometer: ^4.1.1
  syncfusion_flutter_pdf: ^28.1.33
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.4
  flutter_gen_runner: ^5.12.0
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
